name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    environment: "dev"
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Sonarqube Scan
        env:
            SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run:  mvn -DskipTests -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=paolo-lulli_eng-excellence -Dsonar.organization=paolo-lulli -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} -Dsonar.host.url=https://sonarcloud.io


      - name: Build with Maven
        run: mvn clean install

      - name: Set commit environment variable
        run: commit_id=$(git rev-parse --short HEAD); echo "COMMIT_ID=${commit_id}" >> $GITHUB_ENV

#      - name: Login to repo for Base Images
#        env:
#          harbor_user: ${{ secrets.HARBOR_USER }}
#          harbor_password: ${{ secrets.HARBOR_PASSWORD }}
#        run: docker login -u ${{ env.harbor_user }} -p ${{ env.harbor_password }} harbor.eu-dev.internal-az.bakery.volvocars.biz

#      - name: Docker Build
#        env:
#          harbor_user: ${{ secrets.HARBOR_USER }}
#          harbor_password: ${{ secrets.HARBOR_PASSWORD }}

#        run: |
#          docker login -u ${{ env.harbor_user }} -p ${{ env.harbor_password }} harbor.eu-dev.internal-az.bakery.volvocars.biz
#          docker image build . -f Dockerfile --tag harbor.eu-dev.internal-az.bakery.volvocars.biz/battery-management/battman-mvp:commit-${{ env.COMMIT_ID }} --build-arg COMMIT_ID=${{ env.COMMIT_ID }}
#          docker push harbor.eu-dev.internal-az.bakery.volvocars.biz/battery-management/battman-mvp:commit-${{ env.COMMIT_ID }}


